# Generated by Django 2.2.1 on 2019-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=None, to='lists.List'),
        ),
    ]
